[package]
name = "send_mail"
version = "0.1.0"
authors = ["Filippo Cucchetto <filippocucchetto@gmail.com>"]

[dependencies]
getopts = "0.2.14"
rustc-serialize = "0.3.19"
hyper = "0.9"

[dependencies.url]
git = "https://github.com/servo/rust-url"
features = ["query_encoding"]